name: trigger-cc-action
on:
  push:
    paths:
      - data/wip/*
  workflow_dispatch:

jobs:
  run-continuous-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: repos
        name: Detecting repos from the changes
        run: |
          REPOS=$(cat data/wip/* | sed ':a;N;$!ba;s/\n/,/g')
          if [ -z "$REPOS"]; then
              echo "::error::Could not find repositories, aborting job"
              exit 0
          else
              echo "::notice:: Linting the following repositories: $REPOS"
              echo "::set-output name=TARGET_REPOS::$REPOS"
          fi

      - id: encode
        name: Encode ruleset as base64
        run: |
          BASE=$(base64 -w0 config/fixer.json)
          echo "::set-output name=BASE_OUTPUT::$BASE"

      - name: Run Linter
        uses: philips-labs/continuous-compliance-action@develop
        with:
          target_repos: ${{ steps.repos.outputs.TARGET_REPOS }}
          gh_token: ${{ secrets.TEMP_TOKEN }}
          ruleset: ${{ steps.encode.outputs.BASE_OUTPUT }}

      - name: Clean temporary directory
        run: |
          rm -rfv data/wip/*
          touch data/wip/.gitkeep

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions